--- 
book_handler: {}
library:
  -
    type: YAMLLibrary
    uri: drlib.yml
servers:
  -
    type: Standard
    uri: 'http://localhost:8085'
    id: 'a_local_server'
    username: 'bob'
    password: 'e'
module: []

user_info: {}

version: 0.010
