#!/usr/bin/perl

# Copyright (C) 2006 Eric L. Wilhelm, OSoft

use lib 'lib';
use dtRdr::Book;
use dtRdr::Plugins;
dtRdr::Plugins->init;

use warnings;
use strict;

my $uri = shift(@ARGV);
(-e $uri) or die 'no $uri';

my $book = dtRdr::Book->new_from_uri($uri);
$book or die;
print ''. ($book->toc->validate_ranges ? 'ok' : 'not ok'), "\n";
